[[redirects]]
  from = "/khuyen-mai-highlands-uu-dai-highlands-voucher-highlands"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/common"
  to = "/index.html"
  status = 200
  force = true